from django.urls import path
from .views import *
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.home, name='hm-home'),
    path('child/<int:pk>/', views.child, name='child-details'),
    path('add_student/', StudentCreateView.as_view(), name='new-student' ),
    path('calendar/', CalendarView.as_view(), name='calendar' ),
    path('child/<int:pk>/update', StudentUpdateView.as_view(), name='update-child'),
    path('children/', views.students, name='view-children'),
    path('selected_children/', views.selected_students, name='selected-children'),
    path('parents/', views.parents, name='parents'),
    path('health_records/', views.health_records, name='health-records'),
    path('disciplinary_records/', views.disciplinary_records, name='disciplinary-records'),
    path('gate_pass/', views.gate_pass, name='gatepass'),
    path('print_gatepass/<int:pk>/<int:id>/', views.print_gatepass, name='print-gatepass'),
    path('parent/<int:pk>/<int:id>/delete/', views.delete_parent, name='delete-parent'),
    path('health/<int:pk>/<int:id>/delete/', views.delete_health, name='delete-health'),
    path('class_delete/<int:pk>/<int:id>/delete/', views.delete_class, name='delete-class'),
    path('requirement/<int:pk>/<int:id>/delete/', views.delete_requirement, name='delete-requirement'),
    path('gatepass/<int:pk>/<int:id>/delete/', views.delete_gatepass, name='delete-gatepass'),
    path('disciplinary/<int:pk>/<int:id>/delete/', views.delete_discipline, name='delete-discipline'),
    path('report/<int:pk>/<int:id>/delete/', views.delete_report, name='delete-report'),
    path('nextof/<int:pk>/<int:id>/delete/', views.delete_tnext, name='delete-tnext'),
    path('subject_teachers/<int:pk>/<int:id>/delete/', views.delete_tsubject, name='delete-tsubject'),
    path('class_teachers/<int:pk>/<int:id>/delete/', views.delete_tclass, name='delete-tclass'),
    path('track_records/<int:pk>/<int:id>/delete/', views.delete_trecord, name='delete-trecord'),
    path('designations/<int:pk>/<int:id>/delete/', views.delete_designation, name='delete-designation'),
    path('qualifications/<int:pk>/<int:id>/delete/', views.delete_qualification, name='delete-qualification'),
    path('leave/<int:pk>/<int:id>/delete/', views.delete_leave, name='delete-leave'),
# Staff----------------------------------------------------
    path('staff/<int:pk>/', views.staff, name='staff-details'),
    path('add_staff/', StaffCreateView.as_view(), name='new-staff' ),
    path('staff/<int:pk>/update', StaffUpdateView.as_view(), name='update-staff'),
    path('all_staff/', StaffListView.as_view(), name='view-staff'),
    path('teaching_staff/', TeachingStaff.as_view(), name='teaching-staff'),
    path('non_teaching_staff/', NonTeachingStaff.as_view(), name='non-teaching-staff'),
    path('subject_teachers/', SubjectTeacherListView.as_view(), name='subject-teachers'),
    path('class_teachers/', ClassTeacherListView.as_view(), name='class-teachers'),
    path('contracts/', ContractListView.as_view(), name='contracts'),
    path('leaves/', LeaveListView.as_view(), name='leaves'),
    path('track_records/', TrackRecordListView.as_view(), name='track-records'),

# Administration----------------------------------------------------
    path('meeting/', MeetingCreateView.as_view(), name='meeting'),
    path('meeting/<int:pk>/update', MeetingUpdateView.as_view(), name='update-meeting'),
    path('meeting/<int:pk>/', views.meeting, name='meeting-details'),
    path('messanger/', views.messanger, name='messanger'),
    path('message/<int:pk>/', views.message_details, name='message-detail'),

# Finance----------------------------------------------------
    path('income/', IncomeCreateView.as_view(), name='income'),
    path('income/<int:pk>/update', IncomeUpdateView.as_view(), name='update-income'),
    path('income_report/', views.income_report, name='income-report'),
    path('choose_income_report/', views.choose_income_report, name='choose-income-report'),
    path('expense/', ExpenseCreateView.as_view(), name='expense'),
    path('expense/<int:pk>/update', ExpenseUpdateView.as_view(), name='update-expense'),
    # path('bill/<int:pk>/', views.bill, name='bill-details'),
    path('bill/', BillCreateView.as_view(), name='bill'),
    path('bill/<int:pk>/update', BillUpdateView.as_view(), name='update-bill'),
    path('choose_bill_report/', views.choose_bill_report, name='choose-bill-report'),
    path('bill_report/', views.bill_report, name='bill-report'),
    path('choose_expense_report/', views.choose_expense_report, name='choose-expense-report'),
    path('expense_report/', views.expense_report, name='expense-report'),
    path('expense/<int:pk>/', views.expense, name='expense-details'),
    path('available_items/', views.available_items, name='available-items'),
    path('used_items/', views.used_items, name='used-items'),
    path('use_items/<int:pk>/', views.use_item, name='use-item'),
    path('items_summary/', views.items_summary, name='items-summary'),
    path('set_fees/', views.set_fees, name='set-fees'),
    path('set_fees/<int:pk>/update', views.update_set_fees, name='update-set-fees'),
    path('set_fees/<int:pk>/delete', views.delete_set_fees, name='delete-set-fees'),
    path('fees/', views.fees, name='fees'),
    path('fees_report/', views.fees_report, name='fees-report'),
    path('choose_fees_report/', views.choose_fees_report, name='choose-fees-report'),
    path('record_fees/<int:pk>/', views.record_fees, name='record_fees'),
    path('update_fees/<int:pk>/', views.update_fees, name='update_fees'),
    path('fees_record/<int:child>/<int:fees_class>/<int:term>/<int:year>/', views.fees_record, name='fees-record'),

# Teacher----------------------------------------------------
    path('choose_subject/', views.choose_subject, name='choose-subject'),
    path('enter_marks/', views.enter_marks, name='enter-marks'),
    path('choose_marks/', views.choose_marks, name='choose-marks'),
    path('view_marks/', views.view_marks, name='view-marks'),
    path('class_choose_review/', views.class_choose_review, name='class-choose-review'),
    path('class_review/', views.class_review, name='class-review'),
    path('subject_choose_review/', views.subject_choose_review, name='subject-choose-review'),
    path('subject_review/', views.subject_review, name='subject-review'),

# Academ----------------------------------------------------
    path('choose_report_cards/', views.choose_report_cards, name='choose-report-cards'),
    path('report_cards/', views.report_cards, name='report-cards'),
    path('choose_review/', views.choose_review, name='choose-review'),
    path('hm_review/', views.hm_review, name='review-performance'),
    path('choose_attendance/', views.choose_attendance, name='choose-attendance'),
    path('track_attendance/', views.track_attendance, name='track-attendance'),
    path('select_attendance/', views.select_attendance, name='select-attendance'),
    path('attendance/', views.attendance, name='attendance'),
    path('select_analysis/', views.select_analysis, name='select-analysis'),
    path('marks_analysis/', views.marks_analysis, name='marks-analysis'),

# Library----------------------------------------------------
    path('books/', BookCreateView.as_view(), name='book'),
    path('books/<int:pk>/', BookUpdateView.as_view(), name='update-book'),
    path('book/<int:pk>/', views.book, name='book-details'),
    path('lend_book/', views.lend_book, name='lend-book'),
    path('return_book/', views.return_book, name='return-book'),
    path('return_book_child/<int:pk>/', views.return_book_child, name='return-book-child'),
    path('return_book_staff/<int:pk>/', views.return_book_staff, name='return-book-staff'),
    path('lend_book_child/<int:pk>/', views.lend_book_child, name='lend-book-child'),
    path('lend_book_staff/<int:pk>/', views.lend_book_staff, name='lend-book-staff'),

# Parent----------------------------------------------------   
    path('my_children/', views.my_children, name='my-children'),
# Settings----------------------------------------------------  
    path('settings/children/', views.set_children, name='set-children'),
    path('settings/staff/', views.set_staff, name='set-staff'), 
    path('settings/finance/', views.set_finance, name='set-finance'), 
    path('settings/inventory/', views.set_inventory, name='set-inventory'), 
    path('settings/library/', views.set_library, name='set-library'), 
    path('settings/general/', views.set_general, name='set-general'), 
    path('settings/academia/', views.set_academia, name='set-academia'),
    path('stream/<int:pk>/delete/', views.delete_stream, name='delete-stream'), 
    path('social/<int:pk>/delete/', views.delete_social, name='delete-social'),
    path('sport/<int:pk>/delete/', views.delete_sport, name='delete-sport'),
    path('hygiene/<int:pk>/delete/', views.delete_hygiene, name='delete-hygiene'),
    path('reading/<int:pk>/delete/', views.delete_reading, name='delete-reading'),
    path('partc/<int:pk>/delete/', views.delete_participation, name='delete-participation'),
    path('leader/<int:pk>/delete/', views.delete_leadership, name='delete-leadership'),
    path('smartness/<int:pk>/delete/', views.delete_smartness, name='delete-smartness'),
    path('position/<int:pk>/delete/', views.delete_position, name='delete-position'),
    path('staff_category/<int:pk>/delete/', views.delete_staff_category, name='delete-staff-category'),
    path('staff_status/<int:pk>/delete/', views.delete_staff_status, name='delete-staff-status'),
    path('scale/<int:pk>/delete/', views.delete_scale, name='delete-scale'),
]
