# Generated by Django 2.2.6 on 2019-12-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0002_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='health_information',
        ),
    ]
