# Generated by Django 2.2.6 on 2020-01-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0008_auto_20200108_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hygiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Smartness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Skill Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Sport Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroomreport',
            name='sickness',
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='hygiene_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Hygiene'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='leadership_kills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Leadership'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='participation_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Participation'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='reading_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Reading'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='smartness_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Smartness'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='social_skills',
            field=models.ManyToManyField(to='hm.SocialSkill'),
        ),
        migrations.AddField(
            model_name='classroomreport',
            name='sports',
            field=models.ManyToManyField(to='hm.Sport'),
        ),
    ]
