# Generated by Django 2.2.6 on 2020-01-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0011_meeting_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
