# Generated by Django 2.2.6 on 2020-01-28 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hm', '0012_auto_20200127_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='nin',
            field=models.CharField(default=1, max_length=200, verbose_name='NIN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='scale',
            field=models.CharField(default=1, max_length=200, verbose_name='Salary Scale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='dis_name',
            field=models.CharField(max_length=45, unique=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='hygiene',
            name='level',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='level',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.FileField(blank=True, null=True, upload_to='agenda'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=models.FileField(blank=True, null=True, upload_to='minutes'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='level',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='level',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='smartness',
            name='level',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='socialskill',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Sport Name'),
        ),
        migrations.AlterField(
            model_name='staffcategory',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='staffstatus',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.IncomeSource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.IntegerField()),
                ('unit_measure', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.ExpenseItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Country'),
        ),
    ]
