# Generated by Django 2.2.6 on 2020-01-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0013_auto_20200128_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='received_from',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
