# Generated by Django 2.2.6 on 2020-01-28 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hm', '0016_expense_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('comment', models.TextField()),
                ('received_by', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploads', models.FileField(blank=True, null=True, upload_to='expense_docs')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.Expense')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
