# Generated by Django 2.2.6 on 2020-01-28 16:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hm.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hm', '0017_useitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_registration',
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default=1, max_length=200, verbose_name='Registration Number'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_registration', models.IntegerField(validators=[django.core.validators.MinValueValidator(2012), hm.models.max_value_current_year])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.Student')),
                ('current_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hm.Classe')),
                ('stream', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Stream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Religion'),
        ),
    ]
