# Generated by Django 2.2.6 on 2020-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0019_auto_20200128_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='classinformation',
            name='reg_no',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Registration Number'),
            preserve_default=False,
        ),
    ]
