# Generated by Django 2.2.6 on 2020-02-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0026_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hm.Stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hm.Stream'),
            preserve_default=False,
        ),
    ]
