# Generated by Django 2.2.6 on 2020-02-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0027_auto_20200204_1149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('subject', 'subject_class', 'term', 'year')},
        ),
    ]
