# Generated by Django 2.2.6 on 2020-02-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0031_choose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='year',
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.ClassInformation'),
        ),
    ]
