# Generated by Django 2.2.6 on 2020-02-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0033_auto_20200205_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='marks_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.Classe', verbose_name='Class'),
        ),
    ]
