# Generated by Django 2.2.6 on 2020-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0034_auto_20200205_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_form',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_class',
            field=models.ManyToManyField(to='hm.Classe'),
        ),
    ]
