# Generated by Django 2.2.6 on 2020-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0035_auto_20200205_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='set_class',
            field=models.ManyToManyField(to='hm.Classe'),
        ),
    ]
