# Generated by Django 2.2.6 on 2020-02-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0044_bookstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendbookchild',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hm.BookStatus'),
        ),
        migrations.AddField(
            model_name='lendbookstaff',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hm.BookStatus'),
        ),
    ]
