# Generated by Django 2.2.6 on 2020-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0045_auto_20200213_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nin',
            field=models.CharField(max_length=200, null=True, verbose_name='NIN'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nin',
            field=models.CharField(max_length=200, null=True, verbose_name='NIN'),
        ),
    ]
