# Generated by Django 2.2.6 on 2020-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0046_auto_20200214_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='nin',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='NIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='nin',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='NIN'),
            preserve_default=False,
        ),
    ]
