# Generated by Django 2.2.6 on 2020-02-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0047_auto_20200214_0007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('child', 'subject', 'term', 'exam_set', 'year', 'marks_class')},
        ),
    ]
