# Generated by Django 2.2.6 on 2020-02-18 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0050_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
