# Generated by Django 2.2.6 on 2020-02-18 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0051_fees_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
