# Generated by Django 2.2.6 on 2020-02-18 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0052_auto_20200218_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
