# Generated by Django 2.2.6 on 2020-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0054_auto_20200218_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='uploads',
            field=models.FileField(blank=True, null=True, upload_to='fees_docs'),
        ),
    ]
