# Generated by Django 2.2.6 on 2020-02-18 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0055_fees_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
