# Generated by Django 2.2.6 on 2020-02-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hm', '0056_auto_20200218_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploads', models.FileField(blank=True, null=True, upload_to='expense_docs')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.BillItem')),
                ('unit_measure', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hm.UnitMeasure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
