# Generated by Django 2.2.6 on 2020-02-19 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0058_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
