# Generated by Django 2.2.6 on 2020-02-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0061_attendance_trackattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackattendance',
            name='attendance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hm.Attendance'),
        ),
    ]
