# Generated by Django 2.2.6 on 2020-02-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0063_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hm.Grade'),
        ),
    ]
