# Generated by Django 2.2.6 on 2020-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0067_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=models.TextField(null=True),
        ),
    ]
