# Generated by Django 2.2.6 on 2020-03-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0070_auto_20200227_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinformation',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default=1, max_length=200, verbose_name='Registration Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hm.Message'),
        ),
    ]
